version: '3.8'

services:
  cypress:
    image: cypress/included:latest
    container_name: cypress_tests
    working_dir: /app
    volumes:
      - .:/app
    command: ["npx", "cypress", "run"]
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
    depends_on:
      - app

  app:
    image: node:18
    container_name: node_app
    working_dir: /app
    volumes:
      - .:/app
    command: ["npm", "start"]
    ports:
      - "3000:3000"
